---
# Настройка сети через sysctl

- name: Развернуть конфигурацию sysctl для PCI DSS
  ansible.builtin.template:
    src: pci.conf.j2
    dest: /etc/sysctl.d/pci.conf
    owner: root
    group: root
    mode: "0644"

- name: Применить sysctl
  ansible.builtin.command: sysctl --system
  changed_when: false