---
# Настройка времени через chrony

- name: Установить chrony
  ansible.builtin.apt:
    name: chrony
    state: present

- name: Развернуть конфигурацию chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart chrony

- name: Включить и запустить chrony
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: yes